### PR TITLE
Use water to manage Windows TAP device

### PR DESCRIPTION
**Pull request by alalamav**
This change delegates the Windows TAP device management to songgao/water library. Its implications are the following:
* Consistent implementations across platforms (Linux and macOS already use water).
* Configures the TAP device IP address and DNS servers statically. Previously these were configured via DHCP. This change is required for water to set the TAP device to TUN mode, allowing it to receive traffic through the specified network (address, mask). Note that both versions of the program need elevation to run `netsh`.
* Allows the user to specify an arbitrary TAP device hardware component ID through the `TunComponentID` flag. Previously, tun2socks would only find OpenVpn's "tap0901" and "tap0801" devices.

### CODE REVIEW

**Comment by eycorsican** [comment]
I may not accept this PR since another project of mine is [relying on the TUN IP address](https://github.com/mellow-io/mellow/blob/03cfdb1886f57900641ec30b9990b028fb6c8cc8/src/main.js#L771) to determine if the interface is up or not, while requiring go-tun2socks to start as admin on Windows would cause some inconsistencies across various platforms (current implementation don't need to run as admin on Windows).

The current implementation works quite well for me, and the implementation in water is obviously using the same code base for prototyping. I don't see other benefits to switch to water.

**Comment by alalamav** [comment]
Thank you for reviewing the PR, @eycorsican.

The requirement to run as admin is equally present in both versions of the code. In particular, [this command](https://github.com/eycorsican/go-tun2socks/blob/master/tun/tun_windows.go#L169)  in the current implementaion requires elevation.

I understand that if the current implementation works well, you wouldn't want to change it. However, this change not only improves the code health of the project, but it also allows the client to specify a custom TAP component ID.

Could you please test this change with your project? I believe it should work equally well; otherwise, I'm happy to iterate on the implementation. My team would much rather keep contributing upsteam than having to fork this project.

**Comment by eycorsican** [comment]
This PR doesn't work for me may due to the missing of the TUN gateway address. Moreover, the original implementation works even those `netsh` commands are commented out.

I tried to add the `gw` to your command, not works, the TUN gateway is still empty.

```go
cmd := exec.Command("netsh", "interface", "ip", "set", "address", name, "static", addr, mask, gw)
```

**Comment by alalamav** [comment]
Thanks for testing. I have a few questions so I understand what's going on.

I see that your project uses the Outline TAP device configuration script (👍), but doesn't assign an IP address to the TAP device on install. However, note that if tun2socks was ever run as admin it would have assigned an IP address through the `netsh` commands.

Without elevation, I'm not sure why assigning a static IP address through the same `DeviceIoControl` command (as done by [water](https://github.com/songgao/water/blob/master/syscalls_windows.go#L213)) would behave any differently than the current [DHCP configuration](https://github.com/eycorsican/go-tun2socks/blob/master/tun/tun_windows.go#L188).

If I may bother you with one more thing, what do you get when you run `netsh interface ip show config %TAP_DEVICE_NAME%`?

**Comment by alalamav** [comment]
@eycorsican, I did some testing on my end and it looks like configuring the TAP device through DHCP (`DeviceIoControl`) does not require admin permissions to work. Static IPs on the other hand require `netsh` and `DeviceIoControl` to set the TAP device to TUN mode. The former needs admin permissions. Although, I think it may be possible to [modify water](https://github.com/songgao/water/blob/master/syscalls_windows.go#L226) to configure TUN mode with the gateway address instead of the network.

I'll close this PR now, but would you be open to accepting a PR to take the TAP component ID as a flag?

Thanks!

**Comment by eycorsican** [comment]
> I'll close this PR now, but would you be open to accepting a PR to take the TAP component ID as a flag?

Sure.

**Pull request closed without merging**
